"use client"

import React from 'react';

interface Option {
    value: string;
    label: string;
}
const dropdownOptions: Option[][] = [
    [
        { value: 'Abidji', label: 'Abidji (abi)' },
        { value: 'Aceh', label: 'Aceh (ace)' },
        { value: 'Achagua', label: 'Achagua (aca)' },
        { value: 'Achang', label: 'Achang (acn)' },
        { value: 'Achi', label: 'Achi (acr)' },
        { value: 'Acholi', label: 'Acholi (ach)' },
        { value: 'Achuar-Shiwiar', label: 'Achuar-Shiwiar (acu)' },
        { value: 'Aché', label: 'Aché (guq)' },
        { value: 'Adele', label: 'Adele (ade)' },
        { value: 'Adioukrou', label: 'Adioukrou (adj)' },
        { value: 'Agarabi', label: 'Agarabi (agd)' },
        { value: 'Aghul', label: 'Aghul (agx)' },
        { value: 'Agutaynen', label: 'Agutaynen (agn)' },
        { value: 'Ahanta', label: 'Ahanta (aha)' },
        { value: 'Akan', label: 'Akan (aka)' },
        { value: 'Akateko', label: 'Akateko (knj)' },
        { value: 'Akawaio', label: 'Akawaio (ake)' },
        { value: 'Akeu', label: 'Akeu (aeu)' },
        { value: 'Akha', label: 'Akha (ahk)' },
        { value: 'Akoose', label: 'Akoose (bss)' },
        { value: 'Alangan', label: 'Alangan (alj)' },
        { value: 'Albanian', label: 'Albanian (sqi)' },
        { value: 'Altai, Southern', label: 'Altai, Southern (alt)' },
        { value: 'Alune', label: 'Alune (alp)' },
        { value: 'Alur', label: 'Alur (alz)' },
        { value: 'Kabyle', label: 'Kabyle (kab)' },
        { value: 'Ambai', label: 'Ambai (amk)' },
        { value: 'Ambrym, North', label: 'Ambrym, North (mmg)' },
        { value: 'Amharic', label: 'Amharic (amh)' },
        { value: 'Amis', label: 'Amis (ami)' },
        { value: 'Amuzgo, San Pedro Amuzgos', label: 'Amuzgo, San Pedro Amuzgos (azg)' },
        { value: 'Angor', label: 'Angor (agg)' },
        { value: 'Anjam', label: 'Anjam (boj)' },
        { value: 'Anufo', label: 'Anufo (cko)' },
        { value: 'Anyin', label: 'Anyin (any)' },
        { value: 'Arabela', label: 'Arabela (arl)' },
        { value: 'Arabic', label: 'Arabic (ara)' },
        { value: 'Aralle-Tabulahan', label: 'Aralle-Tabulahan (atq)' },
        { value: 'Aringa', label: 'Aringa (luc)' },
        { value: 'Armenian, Western', label: 'Armenian, Western (hyw)' },
        { value: 'Arop-Lokep', label: 'Arop-Lokep (apr)' },
        { value: 'Arosi', label: 'Arosi (aia)' },
        { value: 'Aruamu', label: 'Aruamu (msy)' },
        { value: 'Ashᮩnka', label: 'Ashᮩnka (cni)' },
        { value: 'Ash鮩nka, Pajonal', label: 'Ash鮩nka, Pajonal (cjo)' },
        { value: 'Ash鮩nka, Pichis', label: 'Ash鮩nka, Pichis (cpu)' },
        { value: 'Ash鮩nka, Ucayali-Yura', label: 'Ash鮩nka, Ucayali-Yura (cpb)' },
        { value: 'Assamese', label: 'Assamese (asm)' },
        { value: 'Asu', label: 'Asu (asa)' },
        { value: 'Ateso', label: 'Ateso (teo)' },
        { value: 'Atti鍊', label: 'Atti鍊 (ati)' },
        { value: 'Aukan', label: 'Aukan (djk)' },
        { value: 'Avar', label: 'Avar (ava)' },
        { value: 'Avatime', label: 'Avatime (avn)' },
        { value: 'Avokaya', label: 'Avokaya (avu)' },
        { value: 'Awa', label: 'Awa (awb)' },
        { value: 'Awa-Cuaiquer', label: 'Awa-Cuaiquer (kwi)' },
        { value: 'Awadhi', label: 'Awadhi (awa)' },
        { value: 'Awajn', label: 'Awajn (agr)' },
        { value: 'Awakateko', label: 'Awakateko (agu)' },
        { value: 'Aymara, Central', label: 'Aymara, Central (ayr)' },
        { value: 'Ayoreo', label: 'Ayoreo (ayo)' },
        { value: 'Ayta, Abellen', label: 'Ayta, Abellen (abp)' },
        { value: 'Ayta, Mag-Indi', label: 'Ayta, Mag-Indi (blx)' },
        { value: 'Ayta, Mag-antsi', label: 'Ayta, Mag-antsi (sgb)' },
        { value: 'Azerbaijani, North (Cyrillic)', label: 'Azerbaijani, North (Cyrillic) (azj-script_cyrillic)' },
        { value: 'Azerbaijani, North (Latin)', label: 'Azerbaijani, North (Latin) (azj-script_latin)' },
        { value: 'Azerbaijani, South', label: 'Azerbaijani, South (azb)' },
        { value: 'Baatonum', label: 'Baatonum (bba)' },
        { value: 'Bada', label: 'Bada (bhz)' },
        { value: 'Baelelea', label: 'Baelelea (bvc)' },
        { value: 'Bagheli', label: 'Bagheli (bfy)' },
        { value: 'Bagri', label: 'Bagri (bgq)' },
        { value: 'Bahnar', label: 'Bahnar (bdq)' },
        { value: 'Baka', label: 'Baka (bdh)' },
        { value: 'Bakhtiⲩ', label: 'Bakhtiⲩ (bqi)' },
        { value: 'Bakw鍊', label: 'Bakw鍊 (bjw)' },
        { value: 'Balantak', label: 'Balantak (blz)' },
        { value: 'Bali', label: 'Bali (ban)' },
        { value: 'Balochi, Southern (Latin)', label: 'Balochi, Southern (Latin) (bcc-script_latin)' },
        { value: 'Balochi, Southern (Arabic)', label: 'Balochi, Southern (Arabic) (bcc-script_arabic)' },
        { value: 'Bamanankan', label: 'Bamanankan (bam)' },
        { value: 'Bambam', label: 'Bambam (ptu)' },
        { value: 'Bana', label: 'Bana (bcw)' },
        { value: 'Bandial', label: 'Bandial (bqj)' },
        { value: 'Bantoanon', label: 'Bantoanon (bno)' },
        { value: 'Barai', label: 'Barai (bbb)' },
        { value: 'Bari', label: 'Bari (bfa)' },
        { value: 'Baruga', label: 'Baruga (bjz)' },
        { value: 'Bashkort', label: 'Bashkort (bak)' },
        { value: 'Basque', label: 'Basque (eus)' },
        { value: 'Bassa', label: 'Bassa (bsq)' },
        { value: 'Batak Angkola', label: 'Batak Angkola (akb)' },
        { value: 'Batak Dairi', label: 'Batak Dairi (btd)' },
        { value: 'Batak Karo', label: 'Batak Karo (btx)' },
        { value: 'Batak Simalungun', label: 'Batak Simalungun (bts)' },
        { value: 'Batak Toba', label: 'Batak Toba (bbc)' },
        { value: 'Bauzi', label: 'Bauzi (bvz)' },
        { value: 'Bedjond', label: 'Bedjond (bjv)' },
        { value: 'Behoa', label: 'Behoa (bep)' },
        { value: 'Bekwarra', label: 'Bekwarra (bkv)' },
        { value: 'Belize English Creole', label: 'Belize English Creole (bzj)' },
        { value: 'Bemba', label: 'Bemba (bem)' },
        { value: 'Benga', label: 'Benga (bng)' },
        { value: 'Bengali', label: 'Bengali (ben)' },
        { value: 'Berom', label: 'Berom (bom)' },
        { value: 'Bete-Bendi', label: 'Bete-Bendi (btt)' },
        { value: 'Bharia', label: 'Bharia (bha)' },
        { value: 'Bhatri', label: 'Bhatri (bgw)' },
        { value: 'Bhattiyali', label: 'Bhattiyali (bht)' },
        { value: 'Biali', label: 'Biali (beh)' },
        { value: 'Bidayuh, Bau', label: 'Bidayuh, Bau (sne)' },
        { value: 'Bikol, Buhinon', label: 'Bikol, Buhinon (ubl)' },
        { value: 'Bikol, Central', label: 'Bikol, Central (bcl)' },
        { value: 'Bimoba', label: 'Bimoba (bim)' },
        { value: 'Binukid', label: 'Binukid (bkd)' },
        { value: 'Binumarien', label: 'Binumarien (bjr)' },
        { value: 'Birifor, Malba', label: 'Birifor, Malba (bfo)' },
        { value: 'Birifor, Southern', label: 'Birifor, Southern (biv)' },
        { value: 'Bisa', label: 'Bisa (bib)' },
        { value: 'Bislama', label: 'Bislama (bis)' },
        { value: 'Bisu', label: 'Bisu (bzi)' },
        { value: 'Bis㍊', label: 'Bis㍊ (bqp)' },
        { value: 'Blaan, Koronadal', label: 'Blaan, Koronadal (bpr)' },
        { value: 'Blaan, Sarangani', label: 'Blaan, Sarangani (bps)' },
        { value: 'Bobo Madar鬠Southern', label: 'Bobo Madar鬠Southern (bwq)' },
        { value: 'Bodo Parja', label: 'Bodo Parja (bdv)' },
        { value: 'Boko', label: 'Boko (bqc)' },
        { value: 'Bokobaru', label: 'Bokobaru (bus)' },
        { value: 'Bola', label: 'Bola (bnp)' },
        { value: 'Bomu', label: 'Bomu (bmq)' },
        { value: 'Bonggi', label: 'Bonggi (bdg)' },
        { value: 'Bora', label: 'Bora (boa)' },
        { value: 'Borong', label: 'Borong (ksr)' },
        { value: 'Bor', label: 'Bor (bor)' },
        { value: 'Bru, Eastern', label: 'Bru, Eastern (bru)' },
        { value: 'Buamu', label: 'Buamu (box)' },
        { value: 'Buang, Mapos', label: 'Buang, Mapos (bzh)' },
        { value: 'Bughotu', label: 'Bughotu (bgt)' },
        { value: 'Buglere', label: 'Buglere (sab)' },
        { value: 'Bulgarian', label: 'Bulgarian (bul)' },
        { value: 'Buli', label: 'Buli (bwu)' },
        { value: 'Bum', label: 'Bum (bmv)' },
        { value: 'Burmese', label: 'Burmese (mya)' },
        { value: 'Bwanabwana', label: 'Bwanabwana (tte)' },
        { value: 'Cab飡r', label: 'Cab飡r (cjp)' },
        { value: 'Cacua', label: 'Cacua (cbv)' },
        { value: 'Capanahua', label: 'Capanahua (kaq)' },
        { value: 'Caquinte', label: 'Caquinte (cot)' },
        { value: 'Carapana', label: 'Carapana (cbc)' },
        { value: 'Carib', label: 'Carib (car)' },
        { value: 'Catalan', label: 'Catalan (cat)' },
        { value: 'Cebuano', label: 'Cebuano (ceb)' },
        { value: 'Cerma', label: 'Cerma (cme)' },
        { value: 'Chachi', label: 'Chachi (cbi)' },
        { value: 'Chamacoco', label: 'Chamacoco (ceg)' },
        { value: 'Chatino, Eastern Highland', label: 'Chatino, Eastern Highland (cly)' },
        { value: 'Chatino, Nopala', label: 'Chatino, Nopala (cya)' },
        { value: 'Chechen', label: 'Chechen (che)' },
        { value: 'Chhattisgarhi', label: 'Chhattisgarhi (hne)' },
        { value: 'Chichewa', label: 'Chichewa (nya)' },
        { value: 'Chidigo', label: 'Chidigo (dig)' },
        { value: 'Chiduruma', label: 'Chiduruma (dug)' },
        { value: 'Chin, Bawm', label: 'Chin, Bawm (bgr)' },
        { value: 'Chin, Eastern Khumi', label: 'Chin, Eastern Khumi (cek)' },
        { value: 'Chin, Falam', label: 'Chin, Falam (cfm)' },
        { value: 'Chin, Hakha', label: 'Chin, Hakha (cnh)' },
        { value: 'Chin, Matu', label: 'Chin, Matu (hlt)' },
        { value: 'Chin, Mn', label: 'Chin, Mn (mwq)' },
        { value: 'Chin, Tedim', label: 'Chin, Tedim (ctd)' },
        { value: 'Chin, Thado', label: 'Chin, Thado (tcz)' },
        { value: 'Chin, Zyphe', label: 'Chin, Zyphe (zyp)' },
        { value: 'Chinantec, Comaltepec', label: 'Chinantec, Comaltepec (cco)' },
        { value: 'Chinantec, Lalana', label: 'Chinantec, Lalana (cnl)' },
        { value: 'Chinantec, Lealao', label: 'Chinantec, Lealao (cle)' },
        { value: 'Chinantec, Ozumac', label: 'Chinantec, Ozumac (chz)' },
        { value: 'Chinantec, Palantla', label: 'Chinantec, Palantla (cpa)' },
        { value: 'Chinantec, Sochiapam', label: 'Chinantec, Sochiapam (cso)' },
        { value: 'Chinantec, Tepetotutla', label: 'Chinantec, Tepetotutla (cnt)' },
        { value: 'Chinantec, Usila', label: 'Chinantec, Usila (cuc)' },
        { value: 'Chinese, Hakka', label: 'Chinese, Hakka (hak)' },
        { value: 'Chinese, Min Nan', label: 'Chinese, Min Nan (nan)' },
        { value: 'Chingoni', label: 'Chingoni (xnj)' },
        { value: 'Chipaya', label: 'Chipaya (cap)' },
        { value: 'Chiquitano', label: 'Chiquitano (cax)' },
        { value: 'Chittagonian', label: 'Chittagonian (ctg)' },
        { value: 'Chol', label: 'Chol (ctu)' },
        { value: 'Chontal, Tabasco', label: 'Chontal, Tabasco (chf)' },
        { value: 'Chopi', label: 'Chopi (cce)' },
        { value: 'Chorote, Iyojwaja', label: 'Chorote, Iyojwaja (crt)' },
        { value: 'Chorote, Iyowujwa', label: 'Chorote, Iyowujwa (crq)' },
        { value: 'Chuj (San Sebastián Coatán)', label: 'Chuj (San Sebastián Coatán) (cac-dialect_sansebastiᮣoatᮠ)' },
        { value: 'Chuj (San Mateo Ixtatán)', label: 'Chuj (San Mateo Ixtatán) (cac-dialect_sanmateoixtatᮠ)' },
        { value: 'Chukchi', label: 'Chukchi (ckt)' },
        { value: 'Chumburung', label: 'Chumburung (ncu)' },
        { value: 'Churahi', label: 'Churahi (cdj)' },
        { value: 'Chuvash', label: 'Chuvash (chv)' },
        { value: 'Chorti', label: 'Chorti (caa)' },
        { value: 'Cishingini', label: 'Cishingini (asg)' },
        { value: 'Cofᮍ', label: 'Cofᮍ (con)' },
        { value: 'Cora, El Nayar', label: 'Cora, El Nayar (crn)' },
        { value: 'Cora, Santa Teresa', label: 'Cora, Santa Teresa (cok)' },
        { value: 'Cree, Plains (Latin)', label: 'Cree, Plains (Latin) (crk-script_latin)' },
        { value: 'Cree, Plains (Syllabics)', label: 'Cree, Plains (Syllabics) (crk-script_syllabics)' },
        { value: 'Crimean Tatar', label: 'Crimean Tatar (crh)' },
        { value: 'Cuiba', label: 'Cuiba (cui)' },
        { value: 'Daasanach', label: 'Daasanach (dsh)' },
        { value: 'Daba', label: 'Daba (dbq)' },
        { value: 'Dagaare, Southern', label: 'Dagaare, Southern (dga)' },
        { value: 'Dagara, Northern', label: 'Dagara, Northern (dgi)' },
        { value: 'Dagba', label: 'Dagba (dgk)' },
        { value: 'Dan', label: 'Dan (dnj)' },
        { value: 'Dan (Gweetaawu-East)', label: 'Dan (Gweetaawu-East) (dnj-dialect_gweetaawueast)' },
        { value: 'Dan (Blowo-West)', label: 'Dan (Blowo-West) (dnj-dialect_blowowest)' },
        { value: 'Dangal顴', label: 'Dangal顴 (daa)' },
        { value: 'Dani, Mid Grand Valley', label: 'Dani, Mid Grand Valley (dnt)' },
        { value: 'Dani, Western', label: 'Dani, Western (dnw)' },
        { value: 'Dargwa', label: 'Dargwa (dar)' },
        { value: 'Datooga', label: 'Datooga (tcc)' },
        { value: 'Dawro', label: 'Dawro (dwr)' },
        { value: 'Dedua', label: 'Dedua (ded)' },
        { value: 'Deg', label: 'Deg (mzw)' },
        { value: 'Delo', label: 'Delo (ntr)' },
        { value: 'Dendi', label: 'Dendi (ddn)' },
        { value: 'Desano', label: 'Desano (des)' },
        { value: 'Desiya', label: 'Desiya (dso)' },
        { value: 'Dhao', label: 'Dhao (nfa)' },
        { value: 'Dhimal', label: 'Dhimal (dhi)' },
        { value: 'Dida, Yocobou鍊', label: 'Dida, Yocobou鍊 (gud)' },
        { value: 'Didinga', label: 'Didinga (did)' },
        { value: 'Digaro-Mishmi', label: 'Digaro-Mishmi (mhu)' },
        { value: 'Dinka, Northeastern', label: 'Dinka, Northeastern (dip)' },
        { value: 'Dinka, Southwestern', label: 'Dinka, Southwestern (dik)' },
        { value: 'Ditammari', label: 'Ditammari (tbz)' },
        { value: 'Dogon, Toro So', label: 'Dogon, Toro So (dts)' },
        { value: 'Dogos鍊', label: 'Dogos鍊 (dos)' },
        { value: 'Dogri', label: 'Dogri (dgo)' },
        { value: 'Duri', label: 'Duri (mvp)' },
        { value: 'Dutch', label: 'Dutch (nld)' },
        { value: 'Dza', label: 'Dza (jen)' },
        { value: 'Dzongkha', label: 'Dzongkha (dzo)' },
        { value: 'Ede Idaca', label: 'Ede Idaca (idd)' },
        { value: 'Ekajuk', label: 'Ekajuk (eka)' },
        { value: 'Embera Cat', label: 'Embera Cat (cto)' },
        { value: 'EmberᬠNorthern', label: 'EmberᬠNorthern (emp)' },
        { value: 'English', label: 'English (eng)' },
        { value: 'Enxet', label: 'Enxet (enx)' },
        { value: 'Epena', label: 'Epena (sja)' },
        { value: 'Erzya', label: 'Erzya (myv)' },
        { value: 'Ese', label: 'Ese (mcq)' },
        { value: 'Ese Ejja', label: 'Ese Ejja (ese)' },
        { value: 'Evenki', label: 'Evenki (evn)' },
        { value: 'Ezaa', label: 'Ezaa (eza)' },
        { value: 'Fali, South', label: 'Fali, South (fal)' },
        { value: 'Faroese', label: 'Faroese (fao)' },
        { value: 'Fataleka', label: 'Fataleka (far)' },
        { value: 'Fijian', label: 'Fijian (fij)' },
        { value: 'Finnish', label: 'Finnish (fin)' },
        { value: 'Fon', label: 'Fon (fon)' },
        { value: 'Fordata', label: 'Fordata (frd)' },
        { value: 'French', label: 'French (fra)' },
        { value: 'Fulah', label: 'Fulah (ful)' },
        { value: 'Fuliiru', label: 'Fuliiru (flr)' },
        { value: 'Gadaba, Mudhili', label: 'Gadaba, Mudhili (gau)' },
        { value: 'Gaddi', label: 'Gaddi (gbk)' },
        { value: 'Gagauz (Cyrillic)', label: 'Gagauz (Cyrillic) (gag-script_cyrillic)' },
        { value: 'Gagauz (Latin)', label: 'Gagauz (Latin) (gag-script_latin)' },
        { value: 'Galela', label: 'Galela (gbi)' },
        { value: 'Gamo', label: 'Gamo (gmv)' },
        { value: 'Ganda', label: 'Ganda (lug)' },
        { value: 'Gapapaiwa', label: 'Gapapaiwa (pwg)' },
        { value: 'Garo', label: 'Garo (grt)' },
        { value: 'Gbaya', label: 'Gbaya (krs)' },
        { value: 'Gbaya, Southwest', label: 'Gbaya, Southwest (gso)' },
        { value: 'Gela', label: 'Gela (nlg)' },
        { value: 'Gen', label: 'Gen (gej)' },
        { value: 'German, Standard', label: 'German, Standard (deu)' },
        { value: 'Ghari', label: 'Ghari (gri)' },
        { value: 'Gikuyu', label: 'Gikuyu (kik)' },
        { value: 'Gikyode', label: 'Gikyode (acd)' },
        { value: 'Gilaki', label: 'Gilaki (glk)' },
        { value: 'Gofa (Latin)', label: 'Gofa (Latin) (gof-script_latin)' },
        { value: 'Gogo', label: 'Gogo (gog)' },
        { value: 'Gokana', label: 'Gokana (gkn)' },
        { value: 'Gondi, Adilabad', label: 'Gondi, Adilabad (wsg)' },
        { value: 'Gonja', label: 'Gonja (gjn)' },
        { value: 'Gor', label: 'Gor (gqr)' },
        { value: 'Gorontalo', label: 'Gorontalo (gor)' },
        { value: 'Gourmanchéma', label: 'Gourmanchéma (gux)' },
        { value: 'Grebo, Northern', label: 'Grebo, Northern (gbo)' },
        { value: 'Greek', label: 'Greek (ell)' },
        { value: 'Greek, Ancient', label: 'Greek, Ancient (grc)' },
        { value: 'Guahibo', label: 'Guahibo (guh)' },
        { value: 'GuajajᲡ', label: 'GuajajᲡ (gub)' },
        { value: 'Guarani', label: 'Guarani (grn)' },
        { value: 'Guarayu', label: 'Guarayu (gyr)' },
        { value: 'Guayabero', label: 'Guayabero (guo)' },
        { value: 'Gude', label: 'Gude (gde)' },

        { value: 'Gujarati', label: 'Gujarati (guj)' },
        { value: 'Gulay', label: 'Gulay (gvl)' },
        { value: 'Gumuz', label: 'Gumuz (guk)' },
        { value: 'Gungu', label: 'Gungu (rub)' },
        { value: 'Gwahatike', label: 'Gwahatike (dah)' },
        { value: 'Gwere', label: 'Gwere (gwr)' },
        { value: 'Gwichin', label: 'Gwichin (gwi)' },
        { value: 'Haitian Creole', label: 'Haitian Creole (hat)' },
        { value: 'Halbi', label: 'Halbi (hlb)' },
        { value: 'Hamer-Banna', label: 'Hamer-Banna (amf)' },
        { value: 'Hanga', label: 'Hanga (hag)' },
        { value: 'Hanunoo', label: 'Hanunoo (hnn)' },
        { value: 'Haryanvi', label: 'Haryanvi (bgc)' },
        { value: 'Hatam', label: 'Hatam (had)' },
        { value: 'Hausa', label: 'Hausa (hau)' },
        { value: 'Hawaii Pidgin', label: 'Hawaii Pidgin (hwc)' },
        { value: 'Hawu', label: 'Hawu (hvn)' },
        { value: 'Haya', label: 'Haya (hay)' },
        { value: 'Hdi', label: 'Hdi (xed)' },
        { value: 'Hebrew', label: 'Hebrew (heb)' },
        { value: 'Hehe', label: 'Hehe (heh)' },
        { value: 'Hiligaynon', label: 'Hiligaynon (hil)' },
        { value: 'Hindi', label: 'Hindi (hin)' },
        { value: 'Hindi, Fiji', label: 'Hindi, Fiji (hif)' },
        { value: 'Hindustani, Sarnami', label: 'Hindustani, Sarnami (hns)' },
        { value: 'Ho', label: 'Ho (hoc)' },
        { value: 'Holiya', label: 'Holiya (hoy)' },
        { value: 'Huastec (Western Potosino)', label: 'Huastec (Western Potosino) (hus-dialect_westernpotosino)' },
        { value: 'Huastec (Central Veracruz)', label: 'Huastec (Central Veracruz) (hus-dialect_centralveracruz)' },
        { value: 'Huave, San Mateo del Mar', label: 'Huave, San Mateo del Mar (huv)' },
        { value: 'Huli', label: 'Huli (hui)' },
        { value: 'Hungarian', label: 'Hungarian (hun)' },
        { value: 'Hupla', label: 'Hupla (hap)' },
        { value: 'Iban', label: 'Iban (iba)' },
        { value: 'Icelandic', label: 'Icelandic (isl)' },
        { value: 'Idaan', label: 'Idaan (dbj)' },
        { value: 'Ifugao, Amganad', label: 'Ifugao, Amganad (ifa)' },
        { value: 'Ifugao, Batad', label: 'Ifugao, Batad (ifb)' },
        { value: 'Ifugao, Mayoyao', label: 'Ifugao, Mayoyao (ifu)' },
        { value: 'Ifugao, Tuwali', label: 'Ifugao, Tuwali (ifk)' },
        { value: 'If荊', label: 'If荊 (ife)' },
        { value: 'Ignaciano', label: 'Ignaciano (ign)' },
        { value: 'Ika', label: 'Ika (ikk)' },
        { value: 'Ikwo', label: 'Ikwo (iqw)' },
        { value: 'Ila', label: 'Ila (ilb)' },
        { value: 'Ilocano', label: 'Ilocano (ilo)' },
        { value: 'Imbongu', label: 'Imbongu (imo)' },
        { value: 'Indonesian', label: 'Indonesian (ind)' },
        { value: 'Inga', label: 'Inga (inb)' },
        { value: 'Ipili', label: 'Ipili (ipi)' },
        { value: 'Iraqw', label: 'Iraqw (irk)' },
        { value: 'Islander English Creole', label: 'Islander English Creole (icr)' },
        { value: 'Itawit', label: 'Itawit (itv)' },
        { value: 'Itelmen', label: 'Itelmen (itl)' },
        { value: 'Ivbie North-Okpela-Arhe', label: 'Ivbie North-Okpela-Arhe (atg)' },
        { value: 'Ixil (San Juan Cotzal)', label: 'Ixil (San Juan Cotzal) (ixl-dialect_sanjuancotzal)' },
        { value: 'Ixil (San Gaspar Chajul)', label: 'Ixil (San Gaspar Chajul) (ixl-dialect_sangasparchajul)' },
        { value: 'Ixil (Santa María Nebaj)', label: 'Ixil (Santa María Nebaj) (ixl-dialect_santamarianebaj)' },
        { value: 'Iyo', label: 'Iyo (nca)' },
        { value: 'Izere', label: 'Izere (izr)' },
        { value: 'Izii', label: 'Izii (izz)' },
        { value: 'Jakalteko', label: 'Jakalteko (jac)' },
        { value: 'Jamaican English Creole', label: 'Jamaican English Creole (jam)' },
        { value: 'Javanese', label: 'Javanese (jav)' },
        { value: 'Javanese, Suriname', label: 'Javanese, Suriname (jvn)' },
        { value: 'Jingpho', label: 'Jingpho (kac)' },
        { value: 'Jola-Fonyi', label: 'Jola-Fonyi (dyo)' },
        { value: 'Jola-Kasa', label: 'Jola-Kasa (csk)' },
        { value: 'Jopadhola', label: 'Jopadhola (adh)' },
        { value: 'Juang', label: 'Juang (jun)' },
        { value: 'Jukun Takum', label: 'Jukun Takum (jbu)' },
        { value: 'Jula', label: 'Jula (dyu)' },
        { value: 'Jur Modo', label: 'Jur Modo (bex)' },
        { value: 'Juray', label: 'Juray (juy)' },
        { value: 'Kaansa', label: 'Kaansa (gna)' },
        { value: 'Kaapor', label: 'Kaapor (urb)' },
        { value: 'Kabiy荊', label: 'Kabiy荊 (kbp)' },
        { value: 'Kagayanen', label: 'Kagayanen (cgc)' },
        { value: 'Kagulu', label: 'Kagulu (kki)' },
        { value: 'Kaili, Daa', label: 'Kaili, Daa (kzf)' },
        { value: 'Kaili, Ledo', label: 'Kaili, Ledo (lew)' },
        { value: 'Kakataibo-Kashibo', label: 'Kakataibo-Kashibo (cbr)' },
        { value: 'Kako', label: 'Kako (kkj)' },
        { value: 'Kalagan', label: 'Kalagan (keo)' },
        { value: 'Kalanguya', label: 'Kalanguya (kak)' },
        { value: 'Kalinga, Butbut', label: 'Kalinga, Butbut (kyb)' },
        { value: 'Kalinga, Lubuagan', label: 'Kalinga, Lubuagan (knb)' },
        { value: 'Kalinga, Majukayang', label: 'Kalinga, Majukayang (kmd)' },
        { value: 'Kalinga, Tanudan', label: 'Kalinga, Tanudan (kml)' },
        { value: 'Kallahan, Keley-i', label: 'Kallahan, Keley-i (ify)' },
        { value: 'Kalmyk-Oirat', label: 'Kalmyk-Oirat (xal)' },
        { value: 'Kamano', label: 'Kamano (kbq)' },
        { value: 'Kamayurፊ', label: 'Kamayurፊ (kay)' },
        { value: 'Kambaata', label: 'Kambaata (ktb)' },
        { value: 'Kamwe', label: 'Kamwe (hig)' },
        { value: 'Kandawo', label: 'Kandawo (gam)' },
        { value: 'Kandozi-Chapra', label: 'Kandozi-Chapra (cbu)' },
        { value: 'Kangri', label: 'Kangri (xnr)' },
        { value: 'Kanite', label: 'Kanite (kmu)' },
        { value: 'Kankanaey', label: 'Kankanaey (kne)' },
        { value: 'Kannada', label: 'Kannada (kan)' },
        { value: 'Kanuri, Manga', label: 'Kanuri, Manga (kby)' },
        { value: 'Kapampangan', label: 'Kapampangan (pam)' },
        { value: 'Kaqchikel (Santa María Jess)', label: 'Kaqchikel (Santa María Jess) (cak-dialect_santamarejess)' },
        { value: 'Kaqchikel (South Central)', label: 'Kaqchikel (South Central) (cak-dialect_southcentral)' },
        { value: 'Kaqchikel (Yepocapa)', label: 'Kaqchikel (Yepocapa) (cak-dialect_yepocapa)' },
        { value: 'Kaqchikel (Western)', label: 'Kaqchikel (Western) (cak-dialect_western)' },
        { value: 'Kaqchikel (Santa Domingo Xenacoj)', label: 'Kaqchikel (Santa Domingo Xenacoj) (cak-dialect_santodomingoxenacoj)' },
        { value: 'Kaqchikel (Central)', label: 'Kaqchikel (Central) (cak-dialect_central)' },
        { value: 'Karaboro, Eastern', label: 'Karaboro, Eastern (xrb)' },
        { value: 'Karachay-Balkar', label: 'Karachay-Balkar (krc)' },
        { value: 'Karakalpak', label: 'Karakalpak (kaa)' },
        { value: 'Karelian', label: 'Karelian (krl)' },
        { value: 'Karen, Pwo Northern', label: 'Karen, Pwo Northern (pww)' },
        { value: 'Kasem', label: 'Kasem (xsm)' },
        { value: 'Kashinawa', label: 'Kashinawa (cbs)' },
        { value: 'Kaulong', label: 'Kaulong (pss)' },
        { value: 'Kawayaw', label: 'Kawayaw (kxf)' },
        { value: 'Kayab퍊', label: 'Kayab퍊 (kyz)' },
        { value: 'Kayah, Western', label: 'Kayah, Western (kyu)' },
        { value: 'Kayapó', label: 'Kayapó (txu)' },
        { value: 'Kazakh', label: 'Kazakh (kaz)' },
        { value: 'Kebu', label: 'Kebu (ndp)' },
        { value: 'Keliko', label: 'Keliko (kbo)' },
        { value: 'Kenga', label: 'Kenga (kyq)' },
        { value: 'Kenyang', label: 'Kenyang (ken)' },
        { value: 'Kera', label: 'Kera (ker)' },
        { value: 'Ketengban', label: 'Ketengban (xte)' },
        { value: 'Keyagana', label: 'Keyagana (kyg)' },
        { value: 'Khakas', label: 'Khakas (kjh)' },
        { value: 'Khanty', label: 'Khanty (kca)' },
        { value: 'Khmer', label: 'Khmer (khm)' },
        { value: 'Khmer, Northern', label: 'Khmer, Northern (kxm)' },
        { value: 'Khmu', label: 'Khmu (kjg)' },
        { value: 'Kigiryama', label: 'Kigiryama (nyf)' },
        { value: 'Kilivila', label: 'Kilivila (kij)' },
        { value: 'Kim', label: 'Kim (kia)' },
        { value: 'Kimaragang', label: 'Kimaragang (kqr)' },
        { value: 'Kimr鍊', label: 'Kimr鍊 (kqp)' },
        { value: 'Kinaray-a', label: 'Kinaray-a (krj)' },
        { value: 'Kinga', label: 'Kinga (zga)' },
        { value: 'Kinyarwanda', label: 'Kinyarwanda (kin)' },
        { value: 'Kipfokomo', label: 'Kipfokomo (pkb)' },
        { value: 'Kire', label: 'Kire (geb)' },
        { value: 'Kiribati', label: 'Kiribati (gil)' },
        { value: 'Kisar', label: 'Kisar (kje)' },
        { value: 'Kisi, Southern', label: 'Kisi, Southern (kss)' },
        { value: 'Kitharaka', label: 'Kitharaka (thk)' },
        { value: 'Klao', label: 'Klao (klu)' },
        { value: 'Klon', label: 'Klon (kyo)' },
        { value: 'Kogi', label: 'Kogi (kog)' },
        { value: 'Kolami, Northwestern', label: 'Kolami, Northwestern (kfb)' },
        { value: 'Komi-Zyrian', label: 'Komi-Zyrian (kpv)' },
        { value: 'Konab鲩', label: 'Konab鲩 (bbo)' },
        { value: 'Konkomba', label: 'Konkomba (xon)' },
        { value: 'Konkomba', label: 'Konkomba (xon)' },
        { value: 'Kuman', label: 'Kuman (kue)' },
        { value: 'Kumyk', label: 'Kumyk (kum)' },
        { value: 'Kuna, Border', label: 'Kuna, Border (kvn)' },
        { value: 'Kuna, San Blas', label: 'Kuna, San Blas (cuk)' },
        { value: 'Kunda', label: 'Kunda (kdn)' },
        { value: 'Kuo', label: 'Kuo (xuo)' },
        { value: 'Kupia', label: 'Kupia (key)' },
        { value: 'Kupsapiiny', label: 'Kupsapiiny (kpz)' },
        { value: 'Kuranko', label: 'Kuranko (knk)' },
        { value: 'Kurdish, Northern', label: 'Kurdish, Northern (kmr-script_latin)' },
        { value: 'Kurdish, Northern', label: 'Kurdish, Northern (kmr-script_arabic)' },
        { value: 'Kurdish, Northern', label: 'Kurdish, Northern (kmr-script_cyrillic)' },
        { value: 'Kurumba, Alu', label: 'Kurumba, Alu (xua)' },
        { value: 'Kurux', label: 'Kurux (kru)' },
        { value: 'Kusaal', label: 'Kusaal (kus)' },
        { value: 'Kutep', label: 'Kutep (kub)' },
        { value: 'Kuwaataay', label: 'Kuwaataay (cwt)' },
        { value: 'Kwaio', label: 'Kwaio (kwd)' },
        { value: 'Kwamera', label: 'Kwamera (tnk)' },
        { value: 'Kwaraae', label: 'Kwaraae (kwf)' },
        { value: 'Kwere', label: 'Kwere (cwe)' },
        { value: 'Kyaka', label: 'Kyaka (kyc)' },
        { value: 'Kyanga', label: 'Kyanga (tye)' },
        { value: 'Kyrgyz', label: 'Kyrgyz (kir)' },
        { value: 'Kiche (North)', label: 'Kiche (North) (quc-dialect_north)' },
        { value: 'Kiche (East)', label: 'Kiche (East) (quc-dialect_east)' },
        { value: 'Kiche (Central)', label: 'Kiche (Central) (quc-dialect_central)' },
        { value: 'Lacandon', label: 'Lacandon (lac)' },
        { value: 'Lacid', label: 'Lacid (lsi)' },
        { value: 'Ladakhi', label: 'Ladakhi (lbj)' },
        { value: 'Lahu', label: 'Lahu (lhu)' },
        { value: 'Lama', label: 'Lama (las)' },
        { value: 'Lamba', label: 'Lamba (lam)' },
        { value: 'Lamnso', label: 'Lamnso (lns)' },
        { value: 'Lampung Api', label: 'Lampung Api (ljp)' },
        { value: 'Lango', label: 'Lango (laj)' },
        { value: 'Lao', label: 'Lao (lao)' },
        { value: 'Latin', label: 'Latin (lat)' },
        { value: 'Latvian', label: 'Latvian (lav)' },
        { value: 'Lauje', label: 'Lauje (law)' },
        { value: 'Lawa, Western', label: 'Lawa, Western (lcp)' },
        { value: 'Laz', label: 'Laz (lzz)' },
        { value: 'Lele', label: 'Lele (lln)' },
        { value: 'Lelemi', label: 'Lelemi (lef)' },
        { value: 'Lesser Antillean French Creole', label: 'Lesser Antillean French Creole (acf)' },
        { value: 'Lewo', label: 'Lewo (lww)' },
        { value: 'Lhao Vo', label: 'Lhao Vo (mhx)' },
        { value: 'Lik', label: 'Lik (eip)' },
        { value: 'Limba, West-Central', label: 'Limba, West-Central (lia)' },
        { value: 'Limbu', label: 'Limbu (lif)' },
        { value: 'Lingao', label: 'Lingao (onb)' },
        { value: 'Lisu', label: 'Lisu (lis)' },
        { value: 'Lobala', label: 'Lobala (loq)' },
        { value: 'Lobi', label: 'Lobi (lob)' },
        { value: 'Lokaa', label: 'Lokaa (yaz)' },
        { value: 'Loko', label: 'Loko (lok)' },
        { value: 'Lole', label: 'Lole (llg)' },
        { value: 'Lolopo', label: 'Lolopo (ycl)' },
        { value: 'Loma', label: 'Loma (lom)' },
        { value: 'Lomwe', label: 'Lomwe (ngl)' },
        { value: 'Lomwe, Malawi', label: 'Lomwe, Malawi (lon)' },
        { value: 'Luang', label: 'Luang (lex)' },
        { value: 'Lugbara', label: 'Lugbara (lgg)' },
        { value: 'Luguru', label: 'Luguru (ruf)' },
        { value: 'Lukpa', label: 'Lukpa (dop)' },
        { value: 'Lundayeh', label: 'Lundayeh (lnd)' },
        { value: 'Lutos', label: 'Lutos (ndy)' },
        { value: 'Luwo', label: 'Luwo (lwo)' },
        { value: 'Ly鬩', label: 'Ly鬩 (lee)' },
        { value: 'Maan', label: 'Maan (mev)' },
        { value: 'Mabaan', label: 'Mabaan (mfz)' },
        { value: 'Machame', label: 'Machame (jmc)' },
        { value: 'Macuna', label: 'Macuna (myy)' },
        { value: 'Macushi', label: 'Macushi (mbc)' },
        { value: 'Mada', label: 'Mada (mda)' },
        { value: 'Madura', label: 'Madura (mad)' },
        { value: 'Magahi', label: 'Magahi (mag)' },
        { value: 'Mai Brat', label: 'Mai Brat (ayz)' },
        { value: 'Maithili', label: 'Maithili (mai)' },
        { value: 'Maka', label: 'Maka (mca)' },
        { value: 'Makaa', label: 'Makaa (mcp)' },
        { value: 'Makasar', label: 'Makasar (mak)' },
        { value: 'Makhuwa', label: 'Makhuwa (vmw)' },
        { value: 'Makhuwa-Meetto', label: 'Makhuwa-Meetto (mgh)' },
        { value: 'Makonde', label: 'Makonde (kde)' },
        { value: 'Malagasy', label: 'Malagasy (mlg)' },
        { value: 'Malay', label: 'Malay (zlm)' },
        { value: 'Malay, Central', label: 'Malay, Central (pse)' },
        { value: 'Malay, Kupang', label: 'Malay, Kupang (mkn)' },
        { value: 'Malay, Manado', label: 'Malay, Manado (xmm)' },
        { value: 'Malayalam', label: 'Malayalam (mal)' },
        { value: 'Malayic Dayak', label: 'Malayic Dayak (xdy)' },
        { value: 'Maldivian', label: 'Maldivian (div)' },
        { value: 'Male', label: 'Male (mdy)' },
        { value: 'Malvi', label: 'Malvi (mup)' },
        { value: 'Mam (Central)', label: 'Mam (Central) (mam-dialect_central)' },
        { value: 'Mam (Northern)', label: 'Mam (Northern) (mam-dialect_northern)' },
        { value: 'Mam (Southern)', label: 'Mam (Southern) (mam-dialect_southern)' },
        { value: 'Mam (Western)', label: 'Mam (Western) (mam-dialect_western)' },
        { value: 'Mamasa', label: 'Mamasa (mqj)' },
        { value: 'Mambila, Cameroon', label: 'Mambila, Cameroon (mcu)' },
        { value: 'Mambila, Nigeria', label: 'Mambila, Nigeria (mzk)' },
        { value: 'Mampruli', label: 'Mampruli (maw)' },
        { value: 'Mandeali', label: 'Mandeali (mjl)' },
        { value: 'Mandinka', label: 'Mandinka (mnk)' },
        { value: 'Mango', label: 'Mango (mge)' },
        { value: 'Mangseng', label: 'Mangseng (mbh)' },
        { value: 'Mankanya', label: 'Mankanya (knf)' },
        { value: 'Mannan', label: 'Mannan (mjv)' },
        { value: 'Manobo, Matigsalug', label: 'Manobo, Matigsalug (mbt)' },
        { value: 'Manobo, Obo', label: 'Manobo, Obo (obo)' },
        { value: 'Manobo, Western Bukidnon', label: 'Manobo, Western Bukidnon (mbb)' },
        { value: 'Manya', label: 'Manya (mzj)' },
        { value: 'Mapun', label: 'Mapun (sjm)' },
        { value: 'Maranao', label: 'Maranao (mrw)' },
        { value: 'Marathi', label: 'Marathi (mar)' },
        { value: 'Marba', label: 'Marba (mpg)' },
        { value: 'Mari, Meadow', label: 'Mari, Meadow (mhr)' },
        { value: 'Markweeta', label: 'Markweeta (enb)' },
        { value: 'Marshallese', label: 'Marshallese (mah)' },
        { value: 'Masaaba', label: 'Masaaba (myx)' },
        { value: 'Maskelynes', label: 'Maskelynes (klv)' },
        { value: 'Matal', label: 'Matal (mfh)' },
        { value: 'Mato', label: 'Mato (met)' },
        { value: 'Matsigenka', label: 'Matsigenka (mcb)' },
        { value: 'Maya, Mopᮍ', label: 'Maya, Mopᮍ (mop)' },
        { value: 'Maya, Yucatec', label: 'Maya, Yucatec (yua)' },
        { value: 'Mayo', label: 'Mayo (mfy)' },
        { value: 'Mazahua, Central', label: 'Mazahua, Central (maz)' },
        { value: 'Mazatec, Ayautla', label: 'Mazatec, Ayautla (vmy)' },
        { value: 'Mazatec, Chiquihuitlᮍ', label: 'Mazatec, Chiquihuitlᮍ (maq)' },
        { value: 'Mazatec, Ixcatlᮍ', label: 'Mazatec, Ixcatlᮍ (mzi)' },
        { value: 'Mazatec, Jalapa de D', label: 'Mazatec, Jalapa de D (maj)' },
        { value: 'Mazatec, San Jer󮩭o Tec󡴬 (San Antonio)', label: 'Mazatec, San Jer󮩭o Tec󡴬 (San Antonio) (maa-dialect_sanantonio)' },
        { value: 'Mazatec, San Jer󮩭o Tec󡴬 (San Jer󮩭o)', label: 'Mazatec, San Jer󮩭o Tec󡴬 (San Jer󮩭o) (maa-dialect_sanjer󮩭o)' },
        { value: 'Maanyan', label: 'Maanyan (mhy)' },
        { value: 'Madi', label: 'Madi (mhi)' },
        { value: 'Mbandja', label: 'Mbandja (zmz)' },
        { value: 'Mbay', label: 'Mbay (myb)' },
        { value: 'Mbore', label: 'Mbore (gai)' },
        { value: 'Mbuko', label: 'Mbuko (mqb)' },
        { value: 'Mbula-Bwazza', label: 'Mbula-Bwazza (mbu)' },
        { value: 'Melpa', label: 'Melpa (med)' },
        { value: 'Mende', label: 'Mende (men)' },
        { value: 'Mengen', label: 'Mengen (mee)' },
        { value: 'Mentawai', label: 'Mentawai (mwv)' },
        { value: 'Merey', label: 'Merey (meq)' },
        { value: 'Mesme', label: 'Mesme (zim)' },
        { value: 'Meta', label: 'Meta (mgo)' },
        { value: 'Meyah', label: 'Meyah (mej)' },
        { value: 'Migabac', label: 'Migabac (mpp)' },
        { value: 'Minangkabau', label: 'Minangkabau (min)' },
        { value: 'Misak', label: 'Misak (gum)' },
        { value: 'Misima-Panaeati', label: 'Misima-Panaeati (mpx)' },
        { value: 'Mixe, Coatlan', label: 'Mixe, Coatlan (mco)' },
        { value: 'Mixe, Juquila', label: 'Mixe, Juquila (mxq)' },
        { value: 'Mixe, Quetzaltepec', label: 'Mixe, Quetzaltepec (pxm)' },
        { value: 'Mixe, Totontepec', label: 'Mixe, Totontepec (mto)' },
        { value: 'Mixtec, Alacatlatzala', label: 'Mixtec, Alacatlatzala (mim)' },
        { value: 'Mixtec, Alcozauca', label: 'Mixtec, Alcozauca (xta)' },
        { value: 'Mixtec, Amoltepec', label: 'Mixtec, Amoltepec (mbz)' },
        { value: 'Mixtec, Apasco-Apoala', label: 'Mixtec, Apasco-Apoala (mip)' },
        { value: 'Mixtec, Atatlahuca', label: 'Mixtec, Atatlahuca (mib)' },
        { value: 'Mixtec, Ayutla', label: 'Mixtec, Ayutla (miy)' },
        { value: 'Mixtec, Chayuco', label: 'Mixtec, Chayuco (mih)' },
        { value: 'Mixtec, Coatzospan', label: 'Mixtec, Coatzospan (miz)' },
        { value: 'Mixtec, Diuxi-Tilantongo', label: 'Mixtec, Diuxi-Tilantongo (xtd)' },
        { value: 'Mixtec, Jamiltepec', label: 'Mixtec, Jamiltepec (mxt)' },
        { value: 'Mixtec, Magdalena Pe񡳣o', label: 'Mixtec, Magdalena Pe񡳣o (xtm)' },
        { value: 'Mixtec, Metlat󮯣', label: 'Mixtec, Metlat󮯣 (mxv)' },
        { value: 'Mixtec, Northern Tlaxiaco', label: 'Mixtec, Northern Tlaxiaco (xtn)' },
        { value: 'Mixtec, Ocotepec', label: 'Mixtec, Ocotepec (mie)' },
        { value: 'Mixtec, Pe񯬥s', label: 'Mixtec, Pe񯬥s (mil)' },
        { value: 'Mixtec, Pinotepa Nacional', label: 'Mixtec, Pinotepa Nacional (mio)' },
        { value: 'Mixtec, Santa LucMonteverde', label: 'Mixtec, Santa LucMonteverde (mdv)' },
        { value: 'Mixtec, Santa MarZacatepec', label: 'Mixtec, Santa MarZacatepec (mza)' },
        { value: 'Mixtec, Southern Puebla', label: 'Mixtec, Southern Puebla (mit)' },
        { value: 'Mixtec, Tezoatlan', label: 'Mixtec, Tezoatlan (mxb)' },
        { value: 'Mixtec, Yosonda', label: 'Mixtec, Yosonda (mpm)' },
        { value: 'Miyobe', label: 'Miyobe (soy)' },
        { value: 'Mnong, Central', label: 'Mnong, Central (cmo-script_latin)' },
        { value: 'Mnong, Central', label: 'Mnong, Central (cmo-script_khmer)' },
        { value: 'Moba', label: 'Moba (mfq)' },
        { value: 'Mochi', label: 'Mochi (old)' },
        { value: 'Mofu, North', label: 'Mofu, North (mfk)' },
        { value: 'Mofu-Gudur', label: 'Mofu-Gudur (mif)' },
        { value: 'Mokole', label: 'Mokole (mkl)' },
        { value: 'Molima', label: 'Molima (mox)' },
        { value: 'Moma', label: 'Moma (myl)' },
        { value: 'Momuna', label: 'Momuna (mqf)' },
        { value: 'Mon', label: 'Mon (mnw)' },
        { value: 'Mongolian', label: 'Mongolian (mon)' },
        { value: 'Mongondow', label: 'Mongondow (mog)' },
        { value: 'Morisyen', label: 'Morisyen (mfe)' },
        { value: 'Moro', label: 'Moro (mor)' },
        { value: 'Moronene', label: 'Moronene (mqn)' },
        { value: 'Moru', label: 'Moru (mgd)' },
        { value: 'Moskona', label: 'Moskona (mtj)' },
        { value: 'Mro-Khimi', label: 'Mro-Khimi (cmr)' },
        { value: 'Mualang', label: 'Mualang (mtd)' },
        { value: 'Muinane', label: 'Muinane (bmr)' },
        { value: 'Mukulu', label: 'Mukulu (moz)' },
        { value: 'Mumuye', label: 'Mumuye (mzm)' },
        { value: 'Muna', label: 'Muna (mnb)' },
        { value: 'Mundani', label: 'Mundani (mnf)' },
        { value: 'Mundari', label: 'Mundari (unr)' },
        { value: 'Muria, Far Western', label: 'Muria, Far Western (fmu)' },
        { value: 'Murle', label: 'Murle (mur)' },
        { value: 'Murut, Timugon', label: 'Murut, Timugon (tih)' },
        { value: 'Muthuvan', label: 'Muthuvan (muv)' },
        { value: 'Muyang', label: 'Muyang (muy)' },
        { value: 'Mwaghavul', label: 'Mwaghavul (sur)' },
        { value: 'Mwan', label: 'Mwan (moa)' },
        { value: 'Mwani', label: 'Mwani (wmw)' },
        { value: 'M鮩k', label: 'M鮩k (tnr)' },
        { value: 'Mito', label: 'Mito (miq)' },
        { value: 'M򯲩', label: 'M򯲩 (mos)' },
        { value: 'Mnd', label: 'Mnd (muh)' },
        { value: 'Naasioi', label: 'Naasioi (nas)' },
        { value: 'Nad뢍', label: 'Nad뢍 (mbj)' },
        { value: 'Nafaanra', label: 'Nafaanra (nfr)' },
        { value: 'Naga, Kharam', label: 'Naga, Kharam (kfw)' },
        { value: 'Naga, Tangshang', label: 'Naga, Tangshang (nst)' },
        { value: 'Nagamese', label: 'Nagamese (nag)' },
        { value: 'Nahuatl, Central Huasteca', label: 'Nahuatl, Central Huasteca (nch)' },
        { value: 'Nahuatl, Eastern Huasteca', label: 'Nahuatl, Eastern Huasteca (nhe)' },
        { value: 'Nahuatl, Guerrero', label: 'Nahuatl, Guerrero (ngu)' },
        { value: 'Nahuatl, Highland Puebla', label: 'Nahuatl, Highland Puebla (azz)' },
        { value: 'Nahuatl, Isthmus-Mecayapan', label: 'Nahuatl, Isthmus-Mecayapan (nhx)' },
        { value: 'Nahuatl, Michoacᮍ', label: 'Nahuatl, Michoacᮍ (ncl)' },
        { value: 'Nahuatl, Northern Oaxaca', label: 'Nahuatl, Northern Oaxaca (nhy)' },
        { value: 'Nahuatl, Northern Puebla', label: 'Nahuatl, Northern Puebla (ncj)' },
        { value: 'Nahuatl, Sierra Negra', label: 'Nahuatl, Sierra Negra (nsu)' },
        { value: 'Nahuatl, Southeastern Puebla', label: 'Nahuatl, Southeastern Puebla (npl)' },
        { value: 'Nahuatl, Tlamacazapa', label: 'Nahuatl, Tlamacazapa (nuz)' },
        { value: 'Nahuatl, Western Huasteca', label: 'Nahuatl, Western Huasteca (nhw)' },
        { value: 'Nahuatl, ZacatlᮭAhuacatlᮭTepetzintla', label: 'Nahuatl, ZacatlᮭAhuacatlᮭTepetzintla (nhi)' },
        { value: 'Nalca', label: 'Nalca (nlc)' },
        { value: 'NambikuᲡ, Southern', label: 'NambikuᲡ, Southern (nab)' },
        { value: 'Nanai', label: 'Nanai (gld)' },
        { value: 'Nande', label: 'Nande (nnb)' },
        { value: 'Napu', label: 'Napu (npy)' },
        { value: 'Nasa', label: 'Nasa (pbb)' },
        { value: 'Nateni', label: 'Nateni (ntm)' },
        { value: 'Nawdm', label: 'Nawdm (nmz)' },
        { value: 'Nawuri', label: 'Nawuri (naw)' },
        { value: 'Naxi', label: 'Naxi (nxq)' },
        { value: 'Ndamba', label: 'Ndamba (ndj)' },
        { value: 'Ndogo', label: 'Ndogo (ndz)' },
        { value: 'Ndut', label: 'Ndut (ndv)' },
        { value: 'Newar', label: 'Newar (new)' },
        { value: 'Ngaju', label: 'Ngaju (nij)' },
        { value: 'Ngambay', label: 'Ngambay (sba)' },
        { value: 'Ngangam', label: 'Ngangam (gng)' },
        { value: 'Ngbaka', label: 'Ngbaka (nga)' },
        { value: 'Ngindo', label: 'Ngindo (nnq)' },
        { value: 'Ngulu', label: 'Ngulu (ngu)' },
        { value: 'Ng䢥re', label: 'Ng䢥re (gym)' },
        { value: 'Ngakarimojong', label: 'Ngakarimojong (kdj)' },
        { value: 'Nias', label: 'Nias (nia)' },
        { value: 'Nilamba', label: 'Nilamba (nim)' },
        { value: 'Ninzo', label: 'Ninzo (nin)' },
        { value: 'Nkonya', label: 'Nkonya (nko)' },
        { value: 'Nogai', label: 'Nogai (nog)' },
        { value: 'Nomaande', label: 'Nomaande (lem)' },
        { value: 'Nomatsigenga', label: 'Nomatsigenga (not)' },
        { value: 'Nhu', label: 'Nhu (nhu)' },
        { value: 'Ntcham', label: 'Ntcham (bud)' },
        { value: 'Nuer', label: 'Nuer (nus)' },
        { value: 'Nugunu', label: 'Nugunu (yas)' },
        { value: 'Nuni, Southern', label: 'Nuni, Southern (nnw)' },
        { value: 'Nyabwa', label: 'Nyabwa (nwb)' },
        { value: 'Nyakyusa-Ngonde', label: 'Nyakyusa-Ngonde (nyy)' },
        { value: 'Nyankore', label: 'Nyankore (nyn)' },
        { value: 'Nyaturu', label: 'Nyaturu (rim)' },
        { value: 'Nyindrou', label: 'Nyindrou (lid)' },
        { value: 'Nyole', label: 'Nyole (nuj)' },
        { value: 'Nyoro', label: 'Nyoro (nyo)' },
        { value: 'Nzema', label: 'Nzema (nzi)' },
        { value: 'Obolo', label: 'Obolo (ann)' },
        { value: 'Odia', label: 'Odia (ory)' },
        { value: 'Ojibwa, Northwestern', label: 'Ojibwa, Northwestern (ojb-script_latin)' },
        { value: 'Ojibwa, Northwestern', label: 'Ojibwa, Northwestern (ojb-script_syllabics)' },
        { value: 'Oku', label: 'Oku (oku)' },
        { value: 'Oniyan', label: 'Oniyan (bsc)' },
        { value: 'Oroko', label: 'Oroko (bdu)' },
        { value: 'Oromo', label: 'Oromo (orm)' },
        { value: 'Orya', label: 'Orya (ury)' },
        { value: 'Ossetic', label: 'Ossetic (oss)' },
        { value: 'Otomi, Mezquital', label: 'Otomi, Mezquital (ote)' },
        { value: 'Otomi, Quer鴡ro', label: 'Otomi, Quer鴡ro (otq)' },
        { value: 'Owa', label: 'Owa (stn)' },
        { value: 'Paasaal', label: 'Paasaal (sig)' },
        { value: 'Pahari, Kullu', label: 'Pahari, Kullu (kfx)' },
        { value: 'Pahari, Mahasu', label: 'Pahari, Mahasu (bfz)' },
        { value: 'Paicoca', label: 'Paicoca (sey)' },
        { value: 'Paiute, Northern', label: 'Paiute, Northern (pao)' },
        { value: 'Palauan', label: 'Palauan (pau)' },
        { value: 'Palaung, Ruching', label: 'Palaung, Ruching (pce)' },
        { value: 'Palawano, Brookes Point', label: 'Palawano, Brookes Point (plw)' },
        { value: 'Pamona', label: 'Pamona (pmf)' },
        { value: 'Pangasinan', label: 'Pangasinan (pag)' },
        { value: 'Papiamentu', label: 'Papiamentu (pap)' },
        { value: 'Paranan', label: 'Paranan (prf)' },
        { value: 'Parec', label: 'Parec (pab)' },
        { value: 'Parkwa', label: 'Parkwa (pbi)' },
        { value: 'Patamona', label: 'Patamona (pbc)' },
        { value: 'Paumar퍊', label: 'Paumar퍊 (pad)' },
        { value: 'Pele-Ata', label: 'Pele-Ata (ata)' },
        { value: 'Penan, Eastern', label: 'Penan, Eastern (pez)' },
        { value: 'Pengo', label: 'Pengo (peg)' },
        { value: 'Persian', label: 'Persian (fas)' },
        { value: 'Pidgin, Nigerian', label: 'Pidgin, Nigerian (pcm)' },
        { value: 'Pijin', label: 'Pijin (pis)' },
        { value: 'Pinyin', label: 'Pinyin (pny)' },
        { value: 'Piratapuyo', label: 'Piratapuyo (pir)' },
        { value: 'Pitjantjatjara', label: 'Pitjantjatjara (pjt)' },
        { value: 'Pogolo', label: 'Pogolo (poy)' },
        { value: 'Polish', label: 'Polish (pol)' },
        { value: 'Popoloca, San LuTemalacayuca', label: 'Popoloca, San LuTemalacayuca (pps)' },
        { value: 'Popoloca, San Marcos Tlacoyalco', label: 'Popoloca, San Marcos Tlacoyalco (pls)' },
        { value: 'Popoluca, Highland', label: 'Popoluca, Highland (poi)' },
        { value: 'Poqomchi, Eastern', label: 'Poqomchi, Eastern (poh-dialect_eastern)' },
        { value: 'Poqomchi, Western', label: 'Poqomchi, Western (poh-dialect_western)' },
        { value: 'Portuguese', label: 'Portuguese (por)' },
        { value: 'Prai', label: 'Prai (prt)' },
        { value: 'Puinave', label: 'Puinave (pui)' },
        { value: 'Punjabi, Eastern', label: 'Punjabi, Eastern (pan)' },
        { value: 'Purepecha', label: 'Purepecha (tsz)' },
        { value: 'Puroik', label: 'Puroik (suv)' },
        { value: 'P鶩', label: 'P鶩 (lme)' },
        { value: 'Quechua, Ayacucho', label: 'Quechua, Ayacucho (quy)' },
        { value: 'Quechua, Cajamarca', label: 'Quechua, Cajamarca (qvc)' },
        { value: 'Quechua, Cusco', label: 'Quechua, Cusco (quz)' },
        { value: 'Quechua, Eastern Apurc', label: 'Quechua, Eastern Apurc (qve)' },
        { value: 'Quechua, Huallaga', label: 'Quechua, Huallaga (qub)' },
        { value: 'Quechua, Huamal-Dos de Mayo Hu᮵co', label: 'Quechua, Huamal-Dos de Mayo Hu᮵co (qvh)' },
        { value: 'Quechua, Huaylas Ancash', label: 'Quechua, Huaylas Ancash (qwh)' },
        { value: 'Quechua, Huaylla Wanca', label: 'Quechua, Huaylla Wanca (qvw)' },
        { value: 'Quechua, Lambayeque', label: 'Quechua, Lambayeque (quf)' },
        { value: 'Quechua, Margos-Yarowilca-Lauricocha', label: 'Quechua, Margos-Yarowilca-Lauricocha (qvm)' },
        { value: 'Quechua, North Bolivian', label: 'Quechua, North Bolivian (qul)' },
        { value: 'Quechua, North Jun', label: 'Quechua, North Jun (qvn)' },
        { value: 'Quechua, Northern Conchucos Ancash', label: 'Quechua, Northern Conchucos Ancash (qxn)' },
        { value: 'Quechua, Northern Puebla', label: 'Quechua, Northern Puebla (qxh)' },
        { value: 'Quechua, Panao', label: 'Quechua, Panao (qxs)' },
        { value: 'Quechua, San Mart', label: 'Quechua, San Mart (qvs)' },
        { value: 'Quechua, South Bolivian', label: 'Quechua, South Bolivian (quh)' },
        { value: 'Quechua, Southern Conchucos', label: 'Quechua, Southern Conchucos (qxo)' },
        { value: 'Quichua, Ca񡲠Highland', label: 'Quichua, Ca񡲠Highland (qxr)' },
        { value: 'Quichua, Napo', label: 'Quichua, Napo (qvo)' },
        { value: 'Quichua, Northern Pastaza', label: 'Quichua, Northern Pastaza (qvz)' },
        { value: 'Quichua, Salasaca Highland', label: 'Quichua, Salasaca Highland (qxl)' },
        { value: 'Quichua, Tena Lowland', label: 'Quichua, Tena Lowland (quw)' },
        { value: 'Qanjobal', label: 'Qanjobal (kjb)' },
        { value: 'Qeqchi', label: 'Qeqchi (kek)' },
        { value: 'Rabha', label: 'Rabha (rah)' },
        { value: 'Rajbanshi', label: 'Rajbanshi (rjs)' },
        { value: 'Ramoaaina', label: 'Ramoaaina (rai)' },
        { value: 'Rampi', label: 'Rampi (lje)' },
        { value: 'Ranglong', label: 'Ranglong (rnl)' },
        { value: 'Rangpuri', label: 'Rangpuri (rkt)' },
        { value: 'Rapa Nui', label: 'Rapa Nui (rap)' },
        { value: 'Ravula', label: 'Ravula (yea)' },
        { value: 'Rawang', label: 'Rawang (raw)' },
        { value: 'Rejang', label: 'Rejang (rej)' },
        { value: 'Rendille', label: 'Rendille (rel)' },
        { value: 'Riang Lang', label: 'Riang Lang (ril)' },
        { value: 'Rigwe', label: 'Rigwe (iri)' },
        { value: 'Rikou', label: 'Rikou (rgu)' },
        { value: 'Rohingya', label: 'Rohingya (rhg)' },
        { value: 'Romani, Carpathian', label: 'Romani, Carpathian (rmc-script_latin)' },
        { value: 'Romani, Carpathian', label: 'Romani, Carpathian (rmc-script_cyrillic)' },
        { value: 'Romani, Sinte', label: 'Romani, Sinte (rmo)' },
        { value: 'Romani, Vlax', label: 'Romani, Vlax (rmy-script_latin)' },
        { value: 'Romani, Vlax', label: 'Romani, Vlax (rmy-script_cyrillic)' },
        { value: 'Romanian', label: 'Romanian (ron)' },
        { value: 'Romblomanon', label: 'Romblomanon (rol)' },
        { value: 'Ron', label: 'Ron (cla)' },
        { value: 'Ronga', label: 'Ronga (rng)' },
        { value: 'Roviana', label: 'Roviana (rug)' },
        { value: 'Rundi', label: 'Rundi (run)' },
        { value: 'Russian', label: 'Russian (rus)' },
        { value: 'Saamya-Gwe', label: 'Saamya-Gwe (lsm)' },
        { value: 'Sabaot', label: 'Sabaot (spy)' },
        { value: 'Sadri', label: 'Sadri (sck)' },
        { value: 'Sahu', label: 'Sahu (saj)' },
        { value: 'Sakachep', label: 'Sakachep (sch)' },
        { value: 'Sama, Central', label: 'Sama, Central (sml)' },
        { value: 'Sambal', label: 'Sambal (xsb)' },
        { value: 'Sambal, Botolan', label: 'Sambal, Botolan (sbl)' },
        { value: 'Samburu', label: 'Samburu (saq)' },
        { value: 'Samo, Southern', label: 'Samo, Southern (sbd)' },
        { value: 'Samoan', label: 'Samoan (smo)' },
        { value: 'Sampang', label: 'Sampang (rav)' },
        { value: 'Sangir', label: 'Sangir (sxn)' },
        { value: 'Sango', label: 'Sango (sag)' },
        { value: 'Sangu', label: 'Sangu (sbp)' },
        { value: 'Sanumፊ', label: 'Sanumፊ (xsu)' },
        { value: 'Saramaccan', label: 'Saramaccan (srm)' },
        { value: 'Sasak', label: 'Sasak (sas)' },
        { value: 'Saa', label: 'Saa (apb)' },
        { value: 'Sebat Bet Gurage', label: 'Sebat Bet Gurage (sgw)' },
        { value: 'Sedoa', label: 'Sedoa (tvw)' },
        { value: 'Sekpele', label: 'Sekpele (lip)' },
        { value: 'Selaru', label: 'Selaru (slu)' },
        { value: 'Selee', label: 'Selee (snw)' },
        { value: 'Semai', label: 'Semai (sea)' },
        { value: 'Semelai', label: 'Semelai (sza)' },
        { value: 'Sena', label: 'Sena (seh)' },
        { value: 'Seychelles French Creole', label: 'Seychelles French Creole (crs)' },
        { value: 'Shambala', label: 'Shambala (ksb)' },
        { value: 'Shan', label: 'Shan (shn)' },
        { value: 'Shanga', label: 'Shanga (sho)' },
        { value: 'Sharanahua', label: 'Sharanahua (mcd)' },
        { value: 'Shawi', label: 'Shawi (cbt)' },
        { value: 'Sherpa', label: 'Sherpa (xsr)' },
        { value: 'Shilluk', label: 'Shilluk (shk)' },
        { value: 'Shipibo-Conibo', label: 'Shipibo-Conibo (shp)' },
        { value: 'Shona', label: 'Shona (sna)' },
        { value: 'Shor', label: 'Shor (cjs)' },
        { value: 'Shuar', label: 'Shuar (jiv)' },
        { value: 'Siane', label: 'Siane (snp)' },
        { value: 'Siang', label: 'Siang (sya)' },
        { value: 'Sidamo', label: 'Sidamo (sid)' },
        { value: 'Siona', label: 'Siona (snn)' },
        { value: 'Siriano', label: 'Siriano (sri)' },
        { value: 'Sirmauri', label: 'Sirmauri (srx)' },
        { value: 'Sisaala, Tumulung', label: 'Sisaala, Tumulung (sil)' },
        { value: 'Sissala', label: 'Sissala (sld)' },
        { value: 'Siwu', label: 'Siwu (akp)' },
        { value: 'Soga', label: 'Soga (xog)' },
        { value: 'Somali', label: 'Somali (som)' },
        { value: 'Somba-Siawari', label: 'Somba-Siawari (bmu)' },
        { value: 'Songhay, Koyra Chiini', label: 'Songhay, Koyra Chiini (khq)' },
        { value: 'Songhay, Koyraboro Senni', label: 'Songhay, Koyraboro Senni (ses)' },
        { value: 'Sougb', label: 'Sougb (mnx)' },
        { value: 'Spanish', label: 'Spanish (spa)' },
        { value: 'Sranan Tongo', label: 'Sranan Tongo (srn)' },
        { value: 'Suba', label: 'Suba (sxb)' },
        { value: 'Subanon, Western', label: 'Subanon, Western (suc)' },
        { value: 'Sudest', label: 'Sudest (tgo)' },
        { value: 'Sukuma', label: 'Sukuma (suk)' },
        { value: 'Sunda', label: 'Sunda (sun)' },
        { value: 'Sunwar', label: 'Sunwar (suz)' },
        { value: 'Surgujia', label: 'Surgujia (sgj)' },
        { value: 'Susu', label: 'Susu (sus)' },
        { value: 'Swahili', label: 'Swahili (swh)' },
        { value: 'Swedish', label: 'Swedish (swe)' },
        { value: 'Sylheti', label: 'Sylheti (syl)' },
        { value: 'S鮯ufo, Djimini', label: 'S鮯ufo, Djimini (dyi)' },
        { value: 'S鮯ufo, Mamara', label: 'S鮯ufo, Mamara (myk)' },
        { value: 'S鮯ufo, Supyire', label: 'S鮯ufo, Supyire (spp)' },
        { value: 'Taabwa', label: 'Taabwa (tap)' },
        { value: 'Tabaru', label: 'Tabaru (tby)' },
        { value: 'Tacana', label: 'Tacana (tna)' },
        { value: 'Tachelhit', label: 'Tachelhit (shi)' },
        { value: 'Tado', label: 'Tado (klw)' },
        { value: 'Tagalog', label: 'Tagalog (tgl)' },
        { value: 'Tagbanwa, Calamian', label: 'Tagbanwa, Calamian (tbk)' },
        { value: 'Tagin', label: 'Tagin (tgj)' },
        { value: 'Tai Dam', label: 'Tai Dam (blt)' },
        { value: 'Tairora, North', label: 'Tairora, North (tbg)' },
        { value: 'Tairora, South', label: 'Tairora, South (omw)' },
        { value: 'Tajik', label: 'Tajik (tgk)' },
        { value: 'Tajio', label: 'Tajio (tdj)' },
        { value: 'Takia', label: 'Takia (tbc)' },
        { value: 'Talinga-Bwisi', label: 'Talinga-Bwisi (tlj)' },
        { value: 'Talysh', label: 'Talysh (tly)' },
        { value: 'Tamajaq, Tawallammat', label: 'Tamajaq, Tawallammat (ttq-script_tifinagh)' },
        { value: 'Tamil', label: 'Tamil (tam)' },
        { value: 'Tampulma', label: 'Tampulma (tpm)' },
        { value: 'Tangoa', label: 'Tangoa (tgp)' },
        { value: 'Tanna, North', label: 'Tanna, North (tnn)' },
        { value: 'Tarahumara, Western', label: 'Tarahumara, Western (tac)' },
        { value: 'Tarifit', label: 'Tarifit (rif-script_latin)' },
        { value: 'Tarifit', label: 'Tarifit (rif-script_arabic)' },
        { value: 'Tatar', label: 'Tatar (tat)' },
        { value: 'Tatuyo', label: 'Tatuyo (tav)' },
        { value: 'Tawbuid', label: 'Tawbuid (twb)' },
        { value: 'Tboli', label: 'Tboli (tbl)' },
        { value: 'Tehit', label: 'Tehit (kps)' },
        { value: 'Teiwa', label: 'Teiwa (twe)' },
        { value: 'Tektiteko', label: 'Tektiteko (ttc)' },
        { value: 'Telugu', label: 'Telugu (tel)' },
        { value: 'Tem', label: 'Tem (kdh)' },
        { value: 'Tengger', label: 'Tengger (tes)' },
        { value: 'Tennet', label: 'Tennet (tex)' },
        { value: 'Tepehua, Huehuetla', label: 'Tepehua, Huehuetla (tee)' },
        { value: 'Tepehua, Pisaflores', label: 'Tepehua, Pisaflores (tpp)' },
        { value: 'Tepehua, Tlachichilco', label: 'Tepehua, Tlachichilco (tpt)' },
        { value: 'Tepehuan, Southeastern', label: 'Tepehuan, Southeastern (stp)' },
        { value: 'Teribe', label: 'Teribe (tfr)' },
        { value: 'Termanu', label: 'Termanu (twu)' },
        { value: 'Terꮡ', label: 'Terꮡ (ter)' },
        { value: 'Tewa', label: 'Tewa (tew)' },
        { value: 'Thai', label: 'Thai (tha)' },
        { value: 'Thai, Northern', label: 'Thai, Northern (nod)' },
        { value: 'Tharu, Dangaura', label: 'Tharu, Dangaura (thl)' },
        { value: 'Themne', label: 'Themne (tem)' },
        { value: 'Tibetan, Amdo', label: 'Tibetan, Amdo (adx)' },
        { value: 'Tibetan, Central', label: 'Tibetan, Central (bod)' },
        { value: 'Tibetan, Khams', label: 'Tibetan, Khams (khg)' },
        { value: 'Tii', label: 'Tii (tca)' },
        { value: 'Tikar', label: 'Tikar (tik)' },
        { value: 'Tlicho', label: 'Tlicho (dgr)' },
        { value: 'Toba', label: 'Toba (tob)' },
        { value: 'Toba-Maskoy', label: 'Toba-Maskoy (tmf)' },
        { value: 'Tobanga', label: 'Tobanga (tng)' },
        { value: 'Tobelo', label: 'Tobelo (tlb)' },
        { value: 'Tohono Oodham', label: 'Tohono Oodham (ood)' },
        { value: 'Tok Pisin', label: 'Tok Pisin (tpi)' },
        { value: 'Tol', label: 'Tol (jic)' },
        { value: 'Tolaki', label: 'Tolaki (lbw)' },
        { value: 'Tombonuo', label: 'Tombonuo (txa)' },
        { value: 'Tombulu', label: 'Tombulu (tom)' },
        { value: 'Tonga', label: 'Tonga (toh)' },
        { value: 'Tontemboan', label: 'Tontemboan (tnt)' },
        { value: 'Toraja-Sadan', label: 'Toraja-Sadan (sda)' },
        { value: 'Torres Strait Creole', label: 'Torres Strait Creole (tcs)' },
        { value: 'Totonac, Coyutla', label: 'Totonac, Coyutla (toc)' },
        { value: 'Totonac, Highland', label: 'Totonac, Highland (tos)' },
        { value: 'Toura', label: 'Toura (neb)' },
        { value: 'Trinitario', label: 'Trinitario (trn)' },
        { value: 'Triqui, Chicahuaxtla', label: 'Triqui, Chicahuaxtla (trs)' },
        { value: 'Triqui, Copala', label: 'Triqui, Copala (trc)' },
        { value: 'Tri󍊍', label: 'Tri󍊍 (tri)' },
        { value: 'Tsafiki', label: 'Tsafiki (cof)' },
        { value: 'Tsakhur', label: 'Tsakhur (tkr)' },
        { value: 'Tsikimba', label: 'Tsikimba (kdl)' },
        { value: 'Tsiman鍊', label: 'Tsiman鍊 (cas)' },
        { value: 'Tsonga', label: 'Tsonga (tso)' },
        { value: 'Tucano', label: 'Tucano (tuo)' },
        { value: 'Tuma-Irumu', label: 'Tuma-Irumu (iou)' },
        { value: 'Tumak', label: 'Tumak (tmc)' },
        { value: 'Tunebo, Central', label: 'Tunebo, Central (tuf)' },
        { value: 'Turkish', label: 'Turkish (tur)' },
        { value: 'Turkmen', label: 'Turkmen (tuk-script_latin, tuk-script_arabic)' },
        { value: 'Tuwuli', label: 'Tuwuli (bov)' },
        { value: 'Tuyuca', label: 'Tuyuca (tue)' },
        { value: 'Tyap', label: 'Tyap (kcg)' },
        { value: 'Tzeltal', label: 'Tzeltal (tzh-dialect_bachaj󮠿, tzh-dialect_tenejapa)' },
        { value: 'Tzotzil', label: 'Tzotzil (tzo-dialect_chenalh󠿠, tzo-dialect_chamula)' },
        { value: 'Tzutujil', label: 'Tzutujil (tzj-dialect_western, tzj-dialect_eastern)' },
        { value: 'Uab Meto', label: 'Uab Meto (aoz)' },
        { value: 'Udmurt', label: 'Udmurt (udm)' },
        { value: 'Uduk', label: 'Uduk (udu)' },
        { value: 'Ukrainian', label: 'Ukrainian (ukr)' },
        { value: 'Uma', label: 'Uma (ppk)' },
        { value: 'Umbu-Ungu', label: 'Umbu-Ungu (ubu)' },
        { value: 'Urak Lawoi', label: 'Urak Lawoi (urk)' },
        { value: 'Urarina', label: 'Urarina (ura)' },
        { value: 'Urat', label: 'Urat (urt)' },
        { value: 'Urdu', label: 'Urdu (urd-script_devanagari, urd-script_arabic, urd-script_latin)' },
        { value: 'Uripiv-Wala-Rano-Atchin', label: 'Uripiv-Wala-Rano-Atchin (upv)' },
        { value: 'Uspanteko', label: 'Uspanteko (usp)' },
        { value: 'Uyghur', label: 'Uyghur (uig-script_arabic, uig-script_cyrillic)' },
        { value: 'Uzbek', label: 'Uzbek (uzb-script_cyrillic)' },
        { value: 'Vagla', label: 'Vagla (vag)' },
        { value: 'Vengo', label: 'Vengo (bav)' },
        { value: 'Vidunda', label: 'Vidunda (vid)' },
        { value: 'Vietnamese', label: 'Vietnamese (vie)' },
        { value: 'Vili', label: 'Vili (vif)' },
        { value: 'Vunjo', label: 'Vunjo (vun)' },
        { value: 'Vute', label: 'Vute (vut)' },
        { value: 'Wa, Parauk', label: 'Wa, Parauk (prk)' },
        { value: 'Waama', label: 'Waama (wwa)' },
        { value: 'Waima', label: 'Waima (rro)' },
        { value: 'Waimaha', label: 'Waimaha (bao)' },
        { value: 'Waiwai', label: 'Waiwai (waw)' },
        { value: 'Wala', label: 'Wala (lgl)' },
        { value: 'Wali', label: 'Wali (wlx)' },
        { value: 'Wamey', label: 'Wamey (cou)' },
        { value: 'Wamp', label: 'Wamp (hub)' },
        { value: 'Wanano', label: 'Wanano (gvc)' },
        { value: 'Wandala', label: 'Wandala (mfi)' },
        { value: 'Wapishana', label: 'Wapishana (wap)' },
        { value: 'Warao', label: 'Warao (wba)' },
        { value: 'Waray-Waray', label: 'Waray-Waray (war)' },
        { value: 'Wayana', label: 'Wayana (way)' },
        { value: 'Wayuu', label: 'Wayuu (guc)' },
        { value: 'Welsh', label: 'Welsh (cym)' },
        { value: 'Wersing', label: 'Wersing (kvw)' },
        { value: 'Whitesands', label: 'Whitesands (tnp)' },
        { value: 'Witoto, Minika', label: 'Witoto, Minika (hto)' },
        { value: 'Witoto, Murui', label: 'Witoto, Murui (huu)' },
        { value: 'Wolaytta', label: 'Wolaytta (wal-script_latin, wal-script_ethiopic)' },
        { value: 'Wolio', label: 'Wolio (wlo)' },
        { value: 'Woun Meu', label: 'Woun Meu (noa)' },
        { value: 'W蠎orthern', label: 'W蠎orthern (wob)' },
        { value: 'Xaasongaxango', label: 'Xaasongaxango (kao)' },
        { value: 'Xer鮴e', label: 'Xer鮴e (xer)' },
        { value: 'Yagua', label: 'Yagua (yad)' },
        { value: 'Yakan', label: 'Yakan (yka)' },
        { value: 'Yakut', label: 'Yakut (sah)' },
        { value: 'Yala', label: 'Yala (yba)' },
        { value: 'Yali, Angguruk', label: 'Yali, Angguruk (yli)' },
        { value: 'Yali, Ninia', label: 'Yali, Ninia (nlk)' },
        { value: 'Yalunka', label: 'Yalunka (yal)' },
        { value: 'Yamba', label: 'Yamba (yam)' },
        { value: 'Yamdena', label: 'Yamdena (jmd)' },
        { value: 'Yami', label: 'Yami (tao)' },
        { value: 'Yaminahua', label: 'Yaminahua (yaa)' },
        { value: 'Yanesha', label: 'Yanesha (ame)' },
        { value: 'Yanomam', label: 'Yanomam (guu)' },
        { value: 'Yao', label: 'Yao (yao)' },
        { value: 'Yaouré', label: 'Yaouré (yre)' },
        { value: 'Yawa', label: 'Yawa (yva)' },
        { value: 'Yemba', label: 'Yemba (ybb)' },
        { value: 'Yine', label: 'Yine (pib)' },
        { value: 'Yipma', label: 'Yipma (byr)' },
        { value: 'Yom', label: 'Yom (pil)' },
        { value: 'Yoruba', label: 'Yoruba (yor)' },
        { value: 'Yucuna', label: 'Yucuna (ycn)' },
        { value: 'Yupik, Saint Lawrence Island', label: 'Yupik, Saint Lawrence Island (ess)' },
        { value: 'Yuracare', label: 'Yuracare (yuz)' },
        { value: 'Zaiwa', label: 'Zaiwa (atb)' },
        { value: 'Zande', label: 'Zande (zne)' },
        { value: 'Zapotec, Aloapam', label: 'Zapotec, Aloapam (zaq)' },
        { value: 'Zapotec, Amatlán', label: 'Zapotec, Amatlán (zpo)' },
        { value: 'Zapotec, Cajonos', label: 'Zapotec, Cajonos (zad)' },
        { value: 'Zapotec, Choapan', label: 'Zapotec, Choapan (zpc)' },
        { value: 'Zapotec, Coatecas Altas', label: 'Zapotec, Coatecas Altas (zca)' },
        { value: 'Zapotec, Guevea de Humboldt', label: 'Zapotec, Guevea de Humboldt (zpg)' },
        { value: 'Zapotec, Isthmus', label: 'Zapotec, Isthmus (zai)' },
        { value: 'Zapotec, Lachix', label: 'Zapotec, Lachix (zpl)' },
        { value: 'Zapotec, Miahuatlán', label: 'Zapotec, Miahuatlán (zam)' },
        { value: 'Zapotec, Mitla', label: 'Zapotec, Mitla (zaw)' },
        { value: 'Zapotec, Mixtepec', label: 'Zapotec, Mixtepec (zpm)' },
        { value: 'Zapotec, Ocotlán', label: 'Zapotec, Ocotlán (zac)' },
        { value: 'Zapotec, Ozolotepec', label: 'Zapotec, Ozolotepec (zao)' },
        { value: 'Zapotec, Quioquitani-Quierí', label: 'Zapotec, Quioquitani-Quierí (ztq)' },
        { value: 'Zapotec, Rincón', label: 'Zapotec, Rincón (zar)' },
        { value: 'Zapotec, San Vicente Coatlán', label: 'Zapotec, San Vicente Coatlán (zpt)' },
        { value: 'Zapotec, Santa Ana del Valle', label: 'Zapotec, Santa Ana del Valle (zpi)' },
        { value: 'Zapotec, Santo Domingo Albarradas', label: 'Zapotec, Santo Domingo Albarradas (zas)' },
        { value: 'Zapotec, Sierra de Juárez', label: 'Zapotec, Sierra de Juárez (zaa)' },
        { value: 'Zapotec, Texmelucan', label: 'Zapotec, Texmelucan (zpz)' },
        { value: 'Zapotec, Western Tlacolula Valley', label: 'Zapotec, Western Tlacolula Valley (zab)' },
        { value: 'Zapotec, Yalalag', label: 'Zapotec, Yalalag (zpn)' },
        { value: 'Zapotec, Yareni', label: 'Zapotec, Yareni (zar)' },
        { value: 'Zapotec, Yatee', label: 'Zapotec, Yatee (zty)' },
        { value: 'Zapotec, Yatzachi', label: 'Zapotec, Yatzachi (zav)' },
        { value: 'Zaza', label: 'Zaza (zza)' },
        { value: 'Zhuang, Yongbei', label: 'Zhuang, Yongbei (zyb)' },
        { value: 'Zigula', label: 'Zigula (ziw)' },
        { value: 'Zoque, Francisco León', label: 'Zoque, Francisco León (zos)' },
        { value: 'Zulgo-Gemzek', label: 'Zulgo-Gemzek (gnd)' },
        { value: 'ɷ', label: 'ɷ (ewe)' }
    ],
];
interface DropdownProps {
    options: Option[];
}

const DropdownGroup: React.FC<DropdownProps> = ({ options }) => (
    <select className='dubbingSelect border w-full bg-white bg-opacity-5 rounded-lg backdrop-blur-[20px] px-[18px] h-[50px] text-[12px] font-[500] outline-none'>
        {options.map((option, index) => (
            <option key={index} value={option.value}>{option.label}</option>
        ))}
    </select>
);

const DropdownDubbings: React.FC = () => (
    <div className="mt-[32px] ">
        <div className="text-black text-base font-semibold font-['Inter']">Select a Input Language</div>
        <div className='mt-[24px] pb-[22px] space-x-5  relative'>
            {dropdownOptions.map((options, index) => (
                <DropdownGroup key={index} options={options} />
            ))}
        </div>
    </div>
);

export default DropdownDubbings;